### ISSUE TITLE
Couldn't find matching frame capturer for ...

### ISSUE THREAD

**Issue by kvark** [ebkalderon/renderdoc-rs#113]
Downstream - https://github.com/gfx-rs/wgpu/issues/1349
> Core 360000 14:41:59 target_control.cpp(585) Log Got remote handshake: play [360694]
Core 360694 14:41:59 core.cpp(770) Error Couldn't find matching frame capturer for device 0000000000000000 window 0000000000000000 from 0 device frame capturers and 0 frame capturers
Core 360694 14:42:02 core.cpp(770) Error Couldn't find matching frame capturer for device 0000000000000000 window 0000000000000000 from 0 device frame capturers and 0 frame capturers

[Our code](https://github.com/gfx-rs/wgpu/blob/fe07d272b17b9b4ba9934d19fb6cb3120b5ac5ef/player/src/bin/play.rs#L103-L111):
```rust
        rd.start_frame_capture(std::ptr::null(), std::ptr::null());
       // do stuff
        rd.end_frame_capture(std::ptr::null(), std::ptr::null());
```

**Comment by ebkalderon** [comment]
This seems to have been fixed upstream, correct? I think this ticket should be safe to close, but please feel free to post and have this reopened anytime. Thanks for reporting!
