### ISSUE TITLE
Renderdoc prevents usage of debug output

### ISSUE THREAD

**Issue by AlexandreJubert** [ebkalderon/renderdoc-rs#18]
Hello,

I've run into a possible issue, it seems that instancing a new renderdoc endpoint prevents any self defined gl debug output callback to work.

I don't know if it is expected behavior, but maybe it should be documented somewhere.

Please see the following code for repro : (using glutin and gl)

If you remove the renderdoc variable declaration, the error message will appear in the log. Otherwise it won't, even if the debug flags are setted.

```rust

extern "system" fn debug_callback(
    message_source: GLenum,
    message_type: GLenum,
    id: GLuint,
    severity: GLenum,
    length: GLsizei,
    message: *const GLchar,
    user_param: *mut c_void,
) {
    unsafe {
        println!(
            "GL CALLBACK: type {} severity {} message {}",
            message_type,
            severity,
            CStr::from_ptr(message).to_str().unwrap()
        );
    }
}

fn main() {
    let mut renderdoc : RenderDoc<V120> = RenderDoc::new().unwrap("Failed to load rdc");
    let mut events_loop = glutin::EventsLoop::new();
    let window = glutin::WindowBuilder::new()
        .with_title("Hello, world!")
        .with_dimensions(LogicalSize::new(1024.0, 768.0));
    let context = glutin::ContextBuilder::new()
        .with_vsync(false)
        .with_gl_profile(glutin::GlProfile::Core)
        .with_gl_debug_flag(true);
    let gl_window = glutin::GlWindow::new(window, context, &events_loop).unwrap();
    unsafe {
        gl_window.make_current().unwrap();
        gl::load_with(|symbol| gl_window.get_proc_address(symbol) as *const _);
        gl::Enable(gl::DEBUG_OUTPUT);
        gl::Enable(gl::DEBUG_OUTPUT_SYNCHRONOUS);
        gl::DebugMessageCallback(debug_callback, std::ptr::null());
    }
    loop {
        glDebugMessageInsert(GL_DEBUG_SOURCE_APPLICATION, GL_DEBUG_TYPE_ERROR, 0,                       
                     GL_DEBUG_SEVERITY_MEDIUM, -1, "My custom error"); 
        gl_window.swap_buffers().unwrap();
   }
}
```

Thanks for your work on this crate !

Cheers

**Comment by ebkalderon** [comment]
Interesting. Thanks for reporting this issue! I'm not sure if this is the default behavior for Renderdoc or not, but either way it seems strange. I'll have to investigate this further on my own machine and see if I can replicate this behavior.

**Comment by AlexandreJubert** [comment]
Let me know if I can be of any help! I've checked Renderdoc documentation, and it seems that if the flag "Enable API Validation" is enabled, it's overwriting the debug callback: https://renderdoc.org/docs/window/capture_attach.html 

Maybe a workaround would be a new parameter for the constructor ? I can try to submit a PR if it can help you.

**Comment by ebkalderon** [comment]
Sorry for the very delayed response, @AlexandreJubert! I believe that "Enable API Validation" is disabled by default when the API is initialized, though you could confirm on your end whether this is the case by running the following code:

```rust
let enabled = renderdoc.get_capture_option_u32(renderdoc::CaptureOption::ApiValidation);
println!("API validation enabled: {}", enabled);
```

According to the fourth bullet in [this comment](https://github.com/baldurk/renderdoc/issues/1325#issuecomment-476236817) on a related GitHub issue, Renderdoc apparently takes control of all OpenGL debug output and overrides any user-set callbacks before they reach the application. This behavior can be turned off by setting `CaptureOption::DebugOutputMute` to `1`, if it's not already set by default. I hope this fixes your issue!

**Comment by ebkalderon** [comment]
@AlexandreJubert I hope the above information has answered your question and setting `DebugOutputMute` fixed the issue in your project. I will close this issue for now, but please feel free to post an update if you are still running into problems!

**Comment by AlexandreJubert** [comment]
Hi, sorry about the radio silence, I did not have the time to test it as I transitioned from Rust to C++ for this part of my code (and from OpenGL to Vulkan). The C API also have this option and it works properly. Thanks for your time !
