### ISSUE TITLE
Using RenderDoc as a Global

### ISSUE THREAD

**Issue by cwfitzgerald** [ebkalderon/renderdoc-rs#79]
When I first started using this crate, I thought the easiest way to use it was to throw it in a `once_cell::sync::Lazy` and then call it from in there, that way the DLL only gets loaded once, and only if I actually use it, so if I never use it it never gets loaded.

I noticed that because `RenderDoc` is neither Send nor Sync it's impossible to put it in a global at all, even behind a mutex. From what I can tell the renderdoc api requires that some things are single threaded, but not necessarily accessed from the same thread. This should, in theory, allow it to be marked Send, so it could be put globally behind a mutex.

With clone gone, it shouldn't be possible to get more than one handle to renderdoc at a time, which would mean that I believe it would be safe to mark it as Send. I don't know if there are other confounding factors though.

In the mean time, I was able to still use it by creating a new RenderDoc instance every time I needed something done in renderdoc, but this is clunky, and I'd only imagine, slow. I can't store this in any of my state (my renderer is multithreaded behind Arcs and Mutexes) because I need it to all be at least Send.

Besides this comparatively minor issue, things work well, thank you for making these bindings!

**Comment by ebkalderon** [comment]
Hey there, @cwfitzgerald! Thanks for the kind words, and I'm glad the crate was useful to you. ☺️

Unfortunately, I can't find enough information online about whether the in-application API is intended to be thread-local or not. As such, I had marked the struct `!Send` just as a conservative default. But if it can be shown that invoking any part of the API except for `RENDERDOC_GetAPI()` doesn't result in undefined behavior, then I wouldn't mind lifting this restriction.

**Comment by ebkalderon** [comment]
@cwfitzgerald Sorry to ping you directly, but are you still interested in lifting this restriction? I haven't been able to find any documentation which clarifies whether the RenderDoc API entry point is supposed to be thread-local or not, but I was wondering if maybe you had any luck on this.

**Comment by cwfitzgerald** [comment]
I haven't, but let me go poke the renderdoc discord to see if they have any information. I have a hunch that it shouldn't matter, as they know that the dll can be loaded from any thread, and support highly multithreaded apis like vulkan anyway, but I'll see if I can get a more definitive answer from them.

**Comment by cwfitzgerald** [comment]
Welp that was fast. Baldurk himself said that you can call it from any thread, but the api is not reentrant but only one thread at a time. He says a global mutex on the api would work fine, so having things be `Send` but not `Sync` should work perfectly.

**Comment by ebkalderon** [comment]
That's fantastic news! Thanks for the direct confirmation. I'll ship a new release to crates.io right away.

**Comment by ebkalderon** [comment]
Version 0.9.1 has been released to crates.io! :tada: I think this issue should be safe to close now. Thanks for reporting and helping to investigate, @cwfitzgerald. Please feel free to open further issues and PRs if there are other matters you'd like to raise.
